### ISSUE TITLE
No text data specifies post date and modified date

### ISSUE THREAD

**Issue by masuP9** [mirucon/coldbox#18]
Icon specifies post date and modified date but there is no text data.

https://github.com/mirucon/coldbox/blob/1471d2f3ae6946cd134d0c25fcc5d1f9eedf1b78/single.php#L42-L44

And I think better to use `<time>` element also post date.

**Comment by mirucon** [comment]
Fixed the issue with the `<time>` element in 469dd79.
I'm already tracking the issue where the font icons use pseudo elements rather than their own HTML elements in #16, so closing this for now. Thanks for letting me know this!
