### ISSUE TITLE
Menu expanding all items on click

### ISSUE THREAD

**Issue by MemnoCh242** [mirucon/coldbox#62]
I have a menu with multiple (>2) levels. When clicking on a menu item and holding the mouse button down, all items of the current branch are expanded/toggled visible and don\`t get removed when releasing the mouse button. Usually you don\`t see it, because the link is called, but if it was a misclick and you hold down the button and drag the mouse pointer away from the menu, that is quite irritating (but a good way to reproduce the problem).

**Comment by mirucon** [comment]
Thanks, fixed in 517fc48f6b193c5324b601355f1fbe378897da0d and will be released in v1.7.2.
